---
title: "Genome-wide differential gene expression analysis on activated samples of allergic vs control subjects at baseline timepoint (reproducing Fig 4c results from Martino et al)"
output: html_notebook
---


```{r}
# Install packages and load libraries
# install.packages("htmltools")
library(htmltools)

# if (!require("BiocManager", quietly = TRUE))
#      install.packages("BiocManager")
# 
#  BiocManager::install("DESeq2")

library( "DESeq2" )
library(ggplot2)
```
```{r}
# Read in raw counts matrix
# library(readr)
# df <- read_tsv("C:\Users\Amanda Chan\Documents\440 Project\Dataset\GSE114065_raw_counts_GRCh38.p13_NCBI.tsv.gz")

# Unzips gz file and writes over with unzipped version
# R.utils::gunzip("/Users/Amanda Chan/Documents/440 Project/Dataset/GSE114065_raw_counts_GRCh38.p13_NCBI.tsv.gz")
```

```{r}

#countData <- read.table(file = '/Users/Amanda Chan/Documents/440 Project/Dataset/GSE114065_raw_counts_GRCh38.p13_NCBI.tsv', sep = '\t', header = TRUE)
countData <- read.table(file = '..\\..\\data\\raw\\GSE114065_raw_counts_GRCh38.p13_NCBI.tsv', sep = '\t', header = TRUE) # file path: ..\\..\\ goes up two folders 
```


```{r}
head(countData)

```

```{r}
# Unzip Human Gene Annotation Table gz file and write over with unzipped version
# R.utils::gunzip("/Users/Amanda Chan/Documents/440 Project/Dataset/Human.GRCh38.p13.annot.tsv.gz")
```

```{r}
# Unzip metadata gz file and write over with unzipped version
# R.utils::gunzip("/Users/Amanda Chan/Documents/440 Project/Dataset/GSE114065_series_matrix.txt.gz")
```


```{r}

metaData <- read.csv('..\\..\\data\\raw\\GSE114065_series_matrix.csv', header = TRUE, sep = ",")

# countData <- read.table(file = '..\\..\\data\\raw\\GSE114065_raw_counts_GRCh38.p13_NCBI.tsv', sep = '\t', header = TRUE) # file path: ..\\..\\ goes up two folders

metaData
```

```{r}
# Select Sample_geo_accession (1), Sample_characteristics_ch1_age_yrs (10), Sample_characteristics_ch1_allergy_status (13), and Sample_characteristics_ch1_activation_status (14) rows
coldata <- metaData[c("1", "10", "13", "14"),]
coldata

```

```{r}
coldata_transpose <- t(coldata)

```

```{r}
# Remove rows 1 and 2
coldata_transpose_2 <- coldata_transpose[-c(1, 2),]

# Rename columns
colnames(coldata_transpose_2) <- c("geo_accession", "age", "allergy_status","activation_status")
```

```{r}
# Rename rows to GEO accession names
rownames(coldata_transpose_2) <- coldata_transpose_2[,1]

# Delete column 1 since GEO accession names are now row names
coldata_transpose_3 <- coldata_transpose_2[,-1]
```


ALLERGIC VS CONTROL AT BASELINE TIMEPOINT
```{r}

# coldata_transpose_3

# Load dplyr package
library(dplyr)

# Create new metadata table with only samples from the follow-up timepoint (age 2 or 4)
# follow_up_coldata <- filter(coldata_transpose_3, age == '2')
```

```{r}
test_coldata_df <- data.frame(
  age = as.vector(coldata_transpose_3[,1]),
  allergy_status = as.vector(coldata_transpose_3[,2]),
  activation_status = as.vector(coldata_transpose_3[,3]),
  row.names = row.names(coldata_transpose_3)
)

test_coldata_df
```

```{r}
# Create new metadata table with only samples from the baseline timepoint (age 1)
baseline_coldata <- filter(test_coldata_df, age == '1')
# filter(df, state %in% c("CA", "NY",'DE'))

# Of the baseline timepoint data, take the activated datapoints
baseline_act_coldata <- filter(baseline_coldata, activation_status == "1")


# Get sample names of activated samples at the baseline timepoint
sample_label_baseline_act <- row.names(baseline_act_coldata)

```


```{r}
# Create new dataframe with only activated samples from the baseline timepoint (age 1)
# follow_up_countData <- countData[,c("GeneID", sample_label_follow_up)]

baseline_act_countData <- countData[,c("GeneID", sample_label_baseline_act)]

```



```{r}
dds <- DESeqDataSetFromMatrix(countData=baseline_act_countData, 
                              colData=baseline_act_coldata, 
                              design=~allergy_status, tidy = TRUE)
dds
```

```{r}
dds <- DESeq(dds)
```

```{r}
# Look at results table
res <- results(dds, alpha=0.05)
head(results(dds, tidy=TRUE))
```

```{r}
# Summary of results
summary(res) #summary of results

```

```{r}
# Sort summary list by p-value
res <- res[order(res$padj),]
head(res)
```

```{r}
# How many adjusted p-values are less than 0.05
sum(res$padj < 0.05, na.rm=TRUE)

```

```{r}
# How many p-values are less than 0.05
sum(res$pvalue < 0.05, na.rm=TRUE)

```

```{r}
#we can use plotCounts fxn to compare the normalized counts
#between treated and control groups for our top 6 genes
# par(mfrow=c(2,3))
# 
# plotCounts(dds, gene="7476", intgroup="allergy_status")
# plotCounts(dds, gene="10235", intgroup="allergy_status")
# plotCounts(dds, gene="105374981", intgroup="allergy_status")
# plotCounts(dds, gene="348", intgroup="allergy_status")
# plotCounts(dds, gene="255928", intgroup="allergy_status")
# plotCounts(dds, gene="222545", intgroup="allergy_status")

```

Volcano Plot
```{r}
#reset par
par(mfrow=c(1,1))
# Make a basic volcano plot
with(res, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot", xlim=c(-8,6)))

# Add colored points: blue if padj<0.01, red if log2FC>1 and padj<0.05)
with(subset(res, padj<.01 ), points(log2FoldChange, -log10(pvalue), pch=20, col="blue"))
with(subset(res, padj<.01 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))
```
