---
title: "Genome-wide differential gene expression analysis on activated samples of (future) persistent vs resolved subjects at baseline timepoint"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
# Install packages and load libraries
# install.packages("htmltools")
library(htmltools)

# if (!require("BiocManager", quietly = TRUE))
#      install.packages("BiocManager")
# 
#  BiocManager::install("DESeq2")

library( "DESeq2" )
library(ggplot2)
```
```{r}
# Read in raw counts matrix
# library(readr)
# df <- read_tsv("C:\Users\Amanda Chan\Documents\440 Project\Dataset\GSE114065_raw_counts_GRCh38.p13_NCBI.tsv.gz")

# Unzips gz file and writes over with unzipped version
# R.utils::gunzip("/Users/Amanda Chan/Documents/440 Project/Dataset/GSE114065_raw_counts_GRCh38.p13_NCBI.tsv.gz")
```

```{r}


#countData <- read.table(file = '/Users/Amanda Chan/Documents/440 Project/Dataset/GSE114065_raw_counts_GRCh38.p13_NCBI.tsv', sep = '\t', header = TRUE)
countData <- read.table(file = '..\\..\\data\\raw\\GSE114065_raw_counts_GRCh38.p13_NCBI.tsv', sep = '\t', header = TRUE) # file path: ..\\..\\ goes up two folders 
```


```{r}
head(countData)

```

```{r}
# Unzip Human Gene Annotation Table gz file and write over with unzipped version
# R.utils::gunzip("/Users/Amanda Chan/Documents/440 Project/Dataset/Human.GRCh38.p13.annot.tsv.gz")
```

```{r}
# Unzip metadata gz file and write over with unzipped version
# R.utils::gunzip("/Users/Amanda Chan/Documents/440 Project/Dataset/GSE114065_series_matrix.txt.gz")
```


```{r}

metaData <- read.csv('..\\..\\data\\raw\\GSE114065_series_matrix.csv', header = TRUE, sep = ",")

# countData <- read.table(file = '..\\..\\data\\raw\\GSE114065_raw_counts_GRCh38.p13_NCBI.tsv', sep = '\t', header = TRUE) # file path: ..\\..\\ goes up two folders

metaData
```

```{r}
# Select Sample_geo_accession (1), Sample_characteristics_ch1_age_yrs (10), Sample_characteristics_ch1_allergy_status (13), and Sample_characteristics_ch1_activation_status (14) rows
coldata <- metaData[c("1", "10", "13", "14"),]
coldata

```

```{r}
coldata_transpose <- t(coldata)

```

```{r}
# Remove rows 1 and 2
coldata_transpose_2 <- coldata_transpose[-c(1, 2),]

# Rename columns
colnames(coldata_transpose_2) <- c("geo_accession", "age", "allergy_status","activation_status")
```

```{r}
# Rename rows to GEO accession names
rownames(coldata_transpose_2) <- coldata_transpose_2[,1]

# Delete column 1 since GEO accession names are now row names
coldata_transpose_3 <- coldata_transpose_2[,-1]
```


(FUTURE) PERSISTENT VS RESOLVED ALLERGY AT BASELINE TIMEPOINT
```{r}

# coldata_transpose_3

# Load dplyr package
library(dplyr)

# Create new metadata table with only samples from the follow-up timepoint (age 2 or 4)
# follow_up_coldata <- filter(coldata_transpose_3, age == '2')
```

```{r}
test_coldata_df <- data.frame(
  age = as.vector(coldata_transpose_3[,1]),
  allergy_status = as.vector(coldata_transpose_3[,2]),
  activation_status = as.vector(coldata_transpose_3[,3]),
  row.names = row.names(coldata_transpose_3)
)

test_coldata_df
```

```{r}
# Create new metadata table with only samples from the baseline timepoint (age 1)
baseline_coldata <- filter(test_coldata_df, age == '1')

# Of the baseline timepoint data, take the activated datapoints
baseline_act_coldata <- filter(baseline_coldata, activation_status == "1")

# Remove the control datapoints
baseline_act_allerg_coldata <- filter(baseline_act_coldata, allergy_status == "allergic")

```

```{r}
# Reclassify allergy status based on whether allergic subject will be allergy resolved or persistent at the follow-up 
# resolved_sample_label <- 
baseline_act_allerg_coldata[c("GSM3131883", "GSM3131899", "GSM3131919", "GSM3131931", "GSM3131935", "GSM3131945", "GSM3131949", "GSM3131957", "GSM3131961", "GSM3131965", "GSM3131972", "GSM3131976", "GSM3131980", "GSM3131984", "GSM3131990", "GSM3131994", "GSM3132002", "GSM3132010", "GSM3132014"), ]$allergy_status <- "resolved"

baseline_act_allerg_coldata[c("GSM3131927", "GSM3131941", "GSM3131953", "GSM3131968", "GSM3131987", "GSM3131998", "GSM3132006"), ]$allergy_status <- "persistent"


```



```{r}
# Get sample names of activated allergic samples at the baseline timepoint
sample_label_baseline_act_allerg <- row.names(baseline_act_allerg_coldata)

# Create new dataframe with only data samples from the activated allergic samples at baseline timepoint 
# follow_up_countData <- countData[,c("GeneID", sample_label_follow_up)]

baseline_act_allerg_countData <- countData[,c("GeneID", sample_label_baseline_act_allerg)]


```



```{r}
dds <- DESeqDataSetFromMatrix(countData=baseline_act_allerg_countData, 
                              colData=baseline_act_allerg_coldata, 
                              design=~allergy_status, tidy = TRUE)
dds
```

```{r}
dds <- DESeq(dds)
```

```{r}
# Look at results table
res <- results(dds, alpha=0.05)
head(results(dds, tidy=TRUE))
```

```{r}
# Summary of results
summary(res) #summary of results

```
```{r}
# Sort summary list by p-value
res <- res[order(res$padj),]
head(res)
```

```{r}
# How many adjusted p-values are less than 0.05
sum(res$padj < 0.05, na.rm=TRUE)

```
```{r}
# How many p-values are less than 0.05
sum(res$pvalue < 0.05, na.rm=TRUE)

```
```{r}
# Save results to csv
write.csv(as.data.frame(res), 
         file="..\\..\\data\\results\\differential_gene_expression\\activ_pers_vs_resolved_baseline_genomewide.csv")


```


```{r}
#we can use plotCounts fxn to compare the normalized counts
#between treated and control groups for our top 6 genes
par(mfrow=c(2,3))

plotCounts(dds, gene="55803", intgroup="allergy_status")
plotCounts(dds, gene="2254", intgroup="allergy_status")
plotCounts(dds, gene="290", intgroup="allergy_status")
plotCounts(dds, gene="105370259", intgroup="allergy_status")
plotCounts(dds, gene="140738", intgroup="allergy_status")
plotCounts(dds, gene="441501", intgroup="allergy_status")

```
Volcano Plot - pvalues (not adjusted)
```{r}
# #reset par
# par(mfrow=c(1,1))
# # Make a basic volcano plot
# with(res, plot(log2FoldChange, -log10(pvalue), pch=20, main="Volcano plot"))
# 
# # Add colored points: blue if padj<0.05, red if log2FC>2 and padj<0.05)
# with(subset(res, padj<.05 ), points(log2FoldChange, -log10(pvalue), pch=20, col="blue"))
# with(subset(res, padj<.05 & abs(log2FoldChange)>2), points(log2FoldChange, -log10(pvalue), pch=20, col="red"))
```


Volcano Plot - adjusted pvalues
```{r fig.width=7, fig.height=10}

# Save as pdf
pdf(file = "..\\..\\data\\results\\differential_gene_expression\\activ_pers_vs_resolved_baseline_genomewide_volc_plot.pdf", width = 7, height = 10)

# Make volcano plot
with(res, plot(log2FoldChange, -log10(padj), pch=20, xlim=c(-6, 6), main="Differential gene expression in future allergy persistent \n vs allergy resolved infants at baseline timepoint"))

# Add colored points: blue if padj<0.05, red if log2FC>2 and padj<0.05)
with(subset(res, padj<.1 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(padj), pch=20, col="blue"))
with(subset(res, padj<.05 & abs(log2FoldChange)>1), points(log2FoldChange, -log10(padj), pch=20, col="red"))

# Create labels for points
points_label <- subset(res, padj<.1 & abs(log2FoldChange)>1)

# Labels for the significant genes
labels <- c("ADAP2", "FGF9", "ANPEP", "LOC105370259")

# Label the significant genes on the volcano plot
with(points_label[1:2,], text(log2FoldChange, -log10(padj), labels[1:2], pos=3)) 
with(points_label[3,], text(log2FoldChange, -log10(padj), labels[3], pos=4)) 
with(points_label[4,], text(log2FoldChange, -log10(padj), labels[4], pos=1)) 
# pos specifies the position of the labels relative to the points


# Add legend
legend("topright", legend = c("padj < 0.05 and abs(log2FoldChange) > 1", "padj < 0.1 and abs(log2FoldChange) > 1"), col = c("red", "blue"), cex=0.8, pch=20)


dev.off()


```
