---
title: "GSEA on activated samples of (future) persistent vs resolved subjects at baseline timepoint - Food allergy gene set"
output: html_document
date: "2023-04-30"
---

```{r}
library(tidyverse)
```


```{r}
# Read in dge results
res <- read_csv("..\\..\\data\\results\\differential_gene_expression\\activ_pers_vs_resolved_baseline_genomewide.csv")
res
```

```{r}
# Name GeneID column
colnames(res)[1] <- "GeneID"
res
```


```{r}
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("org.Hs.eg.db")
```


```{r}
# Load package
library(org.Hs.eg.db)
```

```{r}
# Convert GeneID column values from numeric to character
res$GeneID <- as.character(res$GeneID)
```


```{r}
# Map Entrez gene IDs to gene symbols
id_to_symbol <- AnnotationDbi::select(
  org.Hs.eg.db, key=res$GeneID,
  columns=c("SYMBOL","GENENAME"), keytype="ENTREZID"
)
id_to_symbol
```

```{r}
# Join gene symbol with results table
res_symb <- inner_join(res, id_to_symbol, by=c("GeneID"="ENTREZID"))
res_symb
```

```{r}
# Create table with just gene symbol and log2fold change to use for GSEA
res_simp <- res_symb %>% 
  dplyr::select(SYMBOL, log2FoldChange) %>% 
  na.omit() %>% 
  distinct() %>% 
  group_by(SYMBOL) 
  
res_simp
```

Fast gsea package
```{r}
# # Install fgsea package
# if (!require("BiocManager", quietly = TRUE))
#     install.packages("BiocManager")
# 
# BiocManager::install("fgsea")

library(fgsea)
```

```{r}
# Create named vector of gene-level statistics
ranks <- deframe(res_simp)
head(ranks, 20)
```

```{r}
# Load the pathways into a named list
pathways.food_allergy <- gmtPathways("..\\..\\gsea\\gene_sets\\HP_FOOD_ALLERGY.v2023.1.Hs.gmt")

# Look at them all if you want (uncomment)
pathways.food_allergy

# Show the first few pathways, and within those, show only the first few genes. 
pathways.food_allergy %>% 
  head() %>% 
  lapply(head)
```

Run the fgsea algorithm
```{r}
# fgseaSimple
# fgseaRes <- fgsea(pathways=pathways.food_allergy, stats=ranks, nperm=1000)
```

```{r}
# fgseaMultilevel (recommended)
fgseaRes <- fgsea(pathways=pathways.food_allergy, stats=ranks)
```


```{r}
fgseaResTidy <- fgseaRes %>%
  as_tibble() %>%
  arrange(desc(NES))

# Show in a nice table:
fgseaResTidy %>% 
  dplyr::select(-leadingEdge, -ES, -nMoreExtreme) %>% 
  arrange(padj) %>% 
  DT::datatable()
```
```{r}
ggplot(fgseaResTidy, aes(reorder(pathway, NES), NES)) +
  geom_col(aes(fill=padj<0.05)) +
  coord_flip() +
  labs(x="Pathway", y="Normalized Enrichment Score",
       title="Hallmark pathways NES from GSEA") + 
  theme_minimal()

```
```{r}
plotEnrichment(pathways.food_allergy[["HP_FOOD_ALLERGY"]],
               ranks)
```

